// <auto-generated />
using System;
namespace Karamel.Backend.Migrations
{
    public static class Migrations
    {
        public static readonly (string Id, string Name)[] List = new[]
        {
            ("20260102_InitialCreate", "InitialCreate")
        };
    }
}
